/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idleclicker;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;


/**
 *
 * @author andre
 */
public class IdleClickerUI extends javax.swing.JFrame {

    /**
     * Creates new form IdleClickerUI
     */
    public IdleClickerUI() {
        initComponents();
        
        //setAllInvisible();
        //Start.setVisible(false);
        clicksPerSecond();
    }
    double count = 0;
    double count2 = 0;
    int cost1 = 100;
    int cost2 = 5;
    int cost3 = 25;
    double cps;
    double cps2;
    int worth = 1;
    int level1 = 0;
    int level2 = 0;
    int level3 = 0;
    int cooldown1 = 30;
    boolean forward = true;
    int reset = 0;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        yes = new javax.swing.JButton();
        no = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Click = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Amount = new javax.swing.JLabel();
        CPS = new javax.swing.JLabel();
        autoclick = new javax.swing.JButton();
        autoclickDesc = new javax.swing.JLabel();
        cooldown1Label = new javax.swing.JLabel();
        shopLabel = new javax.swing.JLabel();
        buy1 = new javax.swing.JButton();
        desc1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        cost1Label = new javax.swing.JLabel();
        level1Label = new javax.swing.JLabel();
        buy2 = new javax.swing.JButton();
        name2 = new javax.swing.JLabel();
        desc2 = new javax.swing.JLabel();
        cost2Label = new javax.swing.JLabel();
        level2Label = new javax.swing.JLabel();
        buy3 = new javax.swing.JButton();
        name3 = new javax.swing.JLabel();
        desc3 = new javax.swing.JLabel();
        cost3Label = new javax.swing.JLabel();
        level3Label = new javax.swing.JLabel();

        jFrame1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jFrame1.setSize(new java.awt.Dimension(1366, 768));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Are you sure?");

        yes.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        no.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        no.setText("No");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1342, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yes)
                .addGap(60, 60, 60)
                .addComponent(no)
                .addGap(581, 581, 581))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yes)
                    .addComponent(no))
                .addGap(318, 318, 318))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Click.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Click.setText("+1");
        Click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickActionPerformed(evt);
            }
        });

        jButton1.setToolTipText("");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Amount.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Amount.setText("0");

        CPS.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CPS.setText("CPS: 0");

        autoclick.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        autoclick.setText("Use Autoclick");
        autoclick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoclickActionPerformed(evt);
            }
        });

        autoclickDesc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        autoclickDesc.setText("Clicks 5 times per second for 10 seconds");

        cooldown1Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cooldown1Label.setText("Cooldown: 30s");

        shopLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        shopLabel.setText("Shop:");

        buy1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        buy1.setText("Buy");
        buy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy1ActionPerformed(evt);
            }
        });

        desc1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        desc1.setText("Doubles the amount each click is worth");

        name1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        name1.setText("Click Worth");

        cost1Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cost1Label.setText("Cost: 100");

        level1Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        level1Label.setText("Current Level: 0");

        buy2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        buy2.setText("Buy");
        buy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy2ActionPerformed(evt);
            }
        });

        name2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        name2.setText("Finger");

        desc2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        desc2.setText("Clicks 0.1 times per second");

        cost2Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cost2Label.setText("Cost: 5");

        level2Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        level2Label.setText("Current Level: 0");

        buy3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        buy3.setText("Buy");
        buy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy3ActionPerformed(evt);
            }
        });

        name3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        name3.setText("Hand");

        desc3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        desc3.setText("Clicks 0.5 times per second");

        cost3Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cost3Label.setText("Cost: 25");

        level3Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        level3Label.setText("Current Level: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Exit)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(578, 578, 578)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Reset))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Click)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(autoclick)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(autoclickDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cooldown1Label))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shopLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cost1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cost2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(buy1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(name1))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(buy2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(name2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGap(49, 49, 49)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(desc1)
                                                    .addComponent(desc2)
                                                    .addComponent(desc3)))
                                            .addComponent(CPS)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cost3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buy3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(280, 280, 280)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(level2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(level1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(level3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Click, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(CPS)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoclick)
                    .addComponent(autoclickDesc)
                    .addComponent(cooldown1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shopLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy1)
                    .addComponent(name1)
                    .addComponent(cost1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(level1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy2)
                    .addComponent(name2)
                    .addComponent(level2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cost2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy3)
                    .addComponent(name3)
                    .addComponent(level3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cost3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Exit)
                            .addComponent(Reset))
                        .addContainerGap())
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickActionPerformed
        count += worth;
        Amount.setText(String.valueOf(count)); 
    }//GEN-LAST:event_ClickActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void buy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy1ActionPerformed
        if(count >= cost1)
        {
            count -= cost1;
            cost1 = cost1 * 4;
            worth = worth * 2;
            cost1Label.setText("Cost: " + String.valueOf(cost1));
            Amount.setText(String.valueOf(count));
            
            Click.setLabel("+" + Integer.toString(worth));
            
            level1 += 1;
            level1Label.setText("Current Level: " + String.valueOf(level1));
        }
    }//GEN-LAST:event_buy1ActionPerformed

    private void autoclickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoclickActionPerformed
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
        @Override
        protected Void doInBackground() throws Exception {
        // Simulate doing something useful.
        if(cooldown1 == 30)
            {
                for(int seconds = 0; seconds < 10; seconds++)
                {
                    if(reset == 1)
                        break;
                    for(int auto = 0; auto < 5; auto++)
                    {
                        if(reset == 1)
                            break;
                        count += worth;
                        Amount.setText(String.valueOf(count));
                        try {
                            Thread.sleep(200);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(IdleClickerUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    if(reset == 1)
                        break;
                    cooldown1--;
                    cooldown1Label.setText("Cooldown: " + String.valueOf(cooldown1) + "s");
                }
                for(int seconds = 10; seconds < 30; seconds++)
                {
                    if(reset == 1)
                        break;
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(IdleClickerUI.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    cooldown1--;
                    cooldown1Label.setText("Cooldown: " + String.valueOf(cooldown1) + "s");
                }
                cooldown1 = 30;
                cooldown1Label.setText("Cooldown: " + String.valueOf(cooldown1) + "s");
            }
                

        return null;
       }
      };
  
    worker.execute();
    }//GEN-LAST:event_autoclickActionPerformed

    private void buy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy2ActionPerformed
        if(count >= cost2)
        {
            count -= cost2;
            cost2 += 5;
            cps += 0.01;
            cps2 += 0.11;
            cost2Label.setText("Cost: " + String.valueOf(cost2));
            Amount.setText(String.valueOf(count));
            
            level2 += 1;
            level2Label.setText("Current Level: " + String.valueOf(level2));
            
            cps2 = Math.floor(cps2 * 10) / 10;
            CPS.setText("CPS: " + String.valueOf(cps2));
        }
    }//GEN-LAST:event_buy2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        count += 1000;
        Amount.setText(String.valueOf(count));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy3ActionPerformed
        if(count >= cost3)
        {
            count -= cost3;
            cost3 += 25;
            cps += 0.05;
            cps2 += 0.51;
            cost3Label.setText("Cost: " + String.valueOf(cost3));
            Amount.setText(String.valueOf(count));
            
            level3 += 1;
            level3Label.setText("Current Level: " + String.valueOf(level3));
            
            cps2 = Math.floor(cps2 * 10) / 10;
            CPS.setText("CPS: " + String.valueOf(cps2));
        }
    }//GEN-LAST:event_buy3ActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
    for(int i = 0; i < 10; i++)
    {
        reset = 1;
        try {
            Thread.sleep(9);
        } catch (InterruptedException ex) {
            Logger.getLogger(IdleClickerUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    count = 0;
    Amount.setText(String.valueOf(count));
    count2 = 0;
    cost1 = 100;
    cost1Label.setText("Cost: " + String.valueOf(cost1));
    cost2 = 5;
    cost2Label.setText("Cost: " + String.valueOf(cost2));
    cost3 = 25;
    cost3Label.setText("Cost: " + String.valueOf(cost3));
    cps = 0;
    cps2 = 0;
    CPS.setText("CPS: " + String.valueOf(cps2));
    worth = 1;
    Click.setLabel("+" + Integer.toString(worth));
    level1 = 0;
    level1Label.setText("Current Level: " + String.valueOf(level1));
    level2 = 0;
    level2Label.setText("Current Level: " + String.valueOf(level2));
    level3 = 0;
    level3Label.setText("Current Level: " + String.valueOf(level3));
    cooldown1 = 30;
    cooldown1Label.setText("Cooldown: " + String.valueOf(cooldown1) + "s");
    forward = true;
    
    jFrame1.setVisible(false);
    this.setVisible(true);
    
    reset = 0;
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        jFrame1.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_noActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        jFrame1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdleClickerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdleClickerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdleClickerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdleClickerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdleClickerUI().setVisible(true);
            }
        });
    }
    
    public void clicksPerSecond()
    {
        SwingWorker<Void, Void> clicks = new SwingWorker<Void, Void>() {
        @Override
        protected Void doInBackground() throws Exception {
        // Simulate doing something useful.
        
        if(cps <= 0.0049)
        {
            while(forward)
            {
                count2 += cps;
                
                if(count2 >= 0.1)
                {
                    count += count2;
                    count2 = 0;
                }
                count = Math.floor(count * 10) / 10;
                Amount.setText(String.valueOf(count));
                Thread.sleep(100);
            }
        }
        else
        {
            while(forward)
            {
                count += cps;
                count = Math.floor(count * 10) / 10;
                Amount.setText(String.valueOf(count));
                Thread.sleep(100);
            }
        }
        
        return null;
       }
      };
  
    clicks.execute();
    }
    
//    public void setAllInvisible()
//    {
//        Start.setVisible(true);
//        
//        Amount.setVisible(false);
//        CPS.setVisible(false);
//        Click.setVisible(false);
//        
//        autoclick.setVisible(false);
//        autoclickDesc.setVisible(false);
//        buy1.setVisible(false);
//        buy2.setVisible(false);
//        buy3.setVisible(false);
//        cooldown1Label.setVisible(false);
//        cost1Label.setVisible(false);
//        cost2Label.setVisible(false);
//        cost3Label.setVisible(false);
//        desc1.setVisible(false);
//        desc2.setVisible(false);
//        desc3.setVisible(false);
//        jButton1.setVisible(false);
//        level1Label.setVisible(false);
//        level2Label.setVisible(false);
//        level3Label.setVisible(false);
//        name1.setVisible(false);
//        name2.setVisible(false);
//        name3.setVisible(false);
//        shopLabel.setVisible(false);
//    }
//    
//    public void setAllVisible()
//    {
//        Start.setVisible(false);
//        
//        Amount.setVisible(true);
//        CPS.setVisible(true);
//        Click.setVisible(true);
//        
//        autoclick.setVisible(true);
//        autoclickDesc.setVisible(true);
//        buy1.setVisible(true);
//        buy2.setVisible(true);
//        buy3.setVisible(true);
//        cooldown1Label.setVisible(true);
//        cost1Label.setVisible(true);
//        cost2Label.setVisible(true);
//        cost3Label.setVisible(true);
//        desc1.setVisible(true);
//        desc2.setVisible(true);
//        desc3.setVisible(true);
//        jButton1.setVisible(true);
//        level1Label.setVisible(true);
//        level2Label.setVisible(true);
//        level3Label.setVisible(true);
//        name1.setVisible(true);
//        name2.setVisible(true);
//        name3.setVisible(true);
//        shopLabel.setVisible(true);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount;
    private javax.swing.JLabel CPS;
    private javax.swing.JButton Click;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Reset;
    private javax.swing.JButton autoclick;
    private javax.swing.JLabel autoclickDesc;
    private javax.swing.JButton buy1;
    private javax.swing.JButton buy2;
    private javax.swing.JButton buy3;
    private javax.swing.JLabel cooldown1Label;
    private javax.swing.JLabel cost1Label;
    private javax.swing.JLabel cost2Label;
    private javax.swing.JLabel cost3Label;
    private javax.swing.JLabel desc1;
    private javax.swing.JLabel desc2;
    private javax.swing.JLabel desc3;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel level1Label;
    private javax.swing.JLabel level2Label;
    private javax.swing.JLabel level3Label;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JButton no;
    private javax.swing.JLabel shopLabel;
    private javax.swing.JButton yes;
    // End of variables declaration//GEN-END:variables
}
